spring:
  application:
    name: labboot-back

  # 資料庫連線設定
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=final;encrypt=true;trustServerCertificate=true
    username: sa
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # Spring Data JPA 設定
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
